language: php
php:
  - 7.0

git:
  depth: 5

sudo: false

matrix:
  fast_finish: true

install: composer install --no-interaction
script:
  - composer test
  - composer cs-check
after_script:
  - composer upload-coverage
